global.__ini_error_string = "";
globalvar INI_SECTION_SIGN_LEFT,INI_SECTION_SIGN_RIGHT,INI_ITEM_SIGN,INI_NOTE_SIGN;
INI_SECTION_SIGN_LEFT = "["
INI_SECTION_SIGN_RIGHT = "]"
INI_ITEM_SIGN = "="
INI_NOTE_SIGN = ";"
